name: Build and Push Docker Images

on:
    push:
        branches:
            - main

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        
        permissions:
          packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push frontend image
              run: |
                docker build -t ghcr.io/${{ github.repository }}/frontend:latest ./frontend
                docker push ghcr.io/${{ github.repository }}/frontend:latest

            - name: Build and push backend image
              run: |
                docker build -t ghcr.io/${{ github.repository }}/backend:latest ./backend
                docker push ghcr.io/${{ github.repository }}/backend:latest
